version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_lab04
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab04
      MYSQL_USER: jjh
      MYSQL_PASSWORD: pass
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./liquibase:/liquibase

volumes:
  db_data: